### ISSUE TITLE
Enable module with Travis support

### ISSUE THREAD

**Issue by phptek** [deviateltd/silverstripe-advancedassets#4]
SilverStripe Travis support works via the https://github.com/silverstripe-labs/silverstripe-travis-support module.

An example .travis.yml file might look like:

```
# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
language: php 
php: 
  - 5.3
  - 5.4
env:
  - DB=MYSQL CORE_RELEASE=3.1
matrix:
  include:
    - php: 5.3
      env: DB=MYSQL
    - php: 5.4
      env: DB=MYSQL

branches:
  master

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: 
  - phpunit silverstripe-cacheable/tests
```
